#set working directory
setwd("")

#Load libraries
library(tidyverse)
library(janitor)
library(lubridate)
library(scrubr)

#Load, clean, transform data--cultivated = yes/no ; native = yes/no

#Load data & reduce to relevant columns
Downy_mildews_tidy <- read.csv(file="DM_Americas_210209-5.csv", header =TRUE)%>%
clean_names() %>%
subset(, select = c(cur_genus,
cur_epithet,
cur_scientific_name,
recorded_by,
year,
month,
day,
cur_host,
host_family,
cultivated,
native_status,
continent,
country,
state_province)) %>%

#Code in cultivated status
mutate(cultivated = case_when(cur_host %in% c("Allium cepa",
"Agastache mexicana",
"Agastache nepetoides",
"Agastache scrophulariifolia",
"Ageratina altissima",
"Agrimonia eupatoria",
"Agropyron cristatum",
"Allium nigrum",
"Allium sativum",
"Allium schoenoprasum",
"Ampelopsis glandulosa",
"Anemone coronaria",
"Anemone hepatica",
"Anemone hepatica var. acuta",
"Antirrhinum majus",
"Arctotis fastuosa",
"Argyranthemum frutescens",
"Armoracia rusticana",
"Artemisia absinthium",
"Artemisia arborescens",
"Artemisia argyrophylla var. brevis",
"Artemisia douglasiana",
"Atropa belladonna",
"Aurinia saxatilis",
"Avena byzantina",
"Avena sativa",
"Barbarea verna",
"Beta vulgaris",
"Brassica juncea",
"Brassica napus",
"Brassica nigra",
"Brassica oleracea",
"Brassica oleracea var. capitata",
"Brassica rapa",
"Callistephus chinensis",
"Camelina sativa",
"Capsicum annuum",
"Cercis canadensis",
"Chenopodium album",
"Chenopodium quinoa",
"Chenopodium berlandieri",
"Chenopodium capitatum",
"Cicer arietinum",
"Clarkia amoena",
"Colocasia antiquorum",
"Coreopsis grandiflora",
"Cucumis anguria",
"Cucumis melo",
"Cucumis sativus",
"Cucurbita maxima",
"Cucurbita moschata",
"Cucurbita pepo",
"Cucurbita pepo subsp ovifera",
"Dactylis glomerata",
"Dianthus caryophyllus",
"Digitalis purpurea",
"Echinocystis lobata",
"Eupatorium purpureum",
"Helianthus annuus",
"Erysimum ◊ cheiri",
"Fagopyrum esculentum",
"Festuca arundinacea",
"Geum chiloense",
"Glycine max",
"Helichrysum bracteatum",
"Hordeum vulgare",
"Humulus lupulus",
"Humulus lupulus var. lupuloides",
"Impatiens arguta",
"Impatiens balsamina",
"Impatiens flanaganae",
"Impatiens hochstetteri",
"Impatiens walleriana",
"Lactuca sativa",
"Lathyrus odoratus",
"Lilium longiflorum",
"Lolium perenne",
"Luffa acutangula",
"Lupinus hartwegii",
"Lycopersicon esculentum",
"Hydrophyllum virginianum",
"Lagenaria siceraria",
"Lupinus bicolor",
"Lupinus densiflorus",
"Lupinus perennis",
"Lupinus polyphyllus",
"Monarda didyma",
"Oenothera biennis",
"Oenothera pallida",
"Oenothera speciosa",
"Papaver nudicaule",
"Matthiola incana",
"Medicago lupulina",
"Medicago sativa",
"Melia azedarach",
"Mesembryanthemum cordifolium",
"Momordica charantia",
"Monoculus hyoseroides",
"Moricandia arvensis",
"Mucuna pruriens var. utilis",
"Nasturtium officinale",
"Nicotiana stocktonii",
"Nicotiana sylvestris",
"Nicotiana tabacum",
"Nicotiana tomentosa",
"Ocimum basilicum",
"Papaver somniferum",
"Penstemon angustifolius",
"Phlox divaricata",
"Phlox paniculata",
"Physostegia virginiana",
"Plantago ovata",
"Plantago princeps var. princeps",
"Parthenocissus tricuspidata",
"Pastinaca sativa",
"Pennisetum glaucum",
"Pilosella aurantiaca",
"Pisum sativum",
"Plantago major",
"Plectranthus scutellarioides",
"Potentilla nepalensis",
"Vitis vulpina",
"Zea mays",
"Vitis aestivalis",
"Vitis aestivalis var. bourquiniana",
"Vitis cordifolia",
"Vitis labrusca",
"Ratibida pinnata",
"Rubus idaeus subsp strigosus",
"Rudbeckia fulgida",
"Rudbeckia hirta",
"Rudbeckia laciniata",
"Rudbeckia sp",
"Rudbeckia triloba",
"Scrophularia marylandica",
"Scrophularia lanceolata",
"Symphyotrichum lateriflorum",
"Symphyotrichum novae-angliae",
"Vitis vinifera",
"Rosa sp",
"Setaria italica",
"Sorghum bicolor",
"Sorghum halepense",
"Vitis 'Lindley' labrusca X vinefera",
"Tarenaya hassleriana",
"Raphanus raphanistrum",
"Raphanus raphanistrum subsp sativus",
"Rheum rhabarbarum",
"Ribes rubrum",
"Ribes uva-crispa",
"Rubus corchorifolius",
"Rubus villosus var. humifusus",
"Scabiosa atropurpurea",
"Scabiosa columbaria",
"Scrophularia nodosa",
"Secale cereale",
"Solanum tuberosum",
"Spilanthes ocymifolia",
"Spinacia oleracea",
"Vaccinium sp",
"Viola bicolor",
"Viola tricolor",
"Viola tricolor f. tenella",
"Vitis bicolor",
"Vitis rotundifolia",
"Vitis rufotomentosa",
"Vitis simpsonii",
"Trichosanthes colubrina",
"Trifolium incarnatum",
"Trifolium repens",
"Trigonella foenum-graecum",
"Triosteum perfoliatum",
"Triticum aestivum",
"Viburnum opulus",
"Viburnum sargentii",
"Viburnum tinus",
"Vicia faba",
"Vicia sativa",
"Vicia sativa subsp nigra",
"Vicia villosa",
"Vigna unguiculata",
"Vitis coignetiae",
"Solidago sphacelata") ~ "cultivated",
cur_host %in% c("Ambrosia artemisiifolia",
"Acalypha virginica",
"Acanthospermum australe",
"Acanthospermum humile",
"Achyronychia cooperi",
"Acmella oppositifolia",
"Acmispon americanus",
"Aconitum columbianum",
"Aconitum delphinifolium",
"Ageratina aromatica",
"Agoseris aurantiaca",
"Agoseris glauca",
"Agoseris grandiflora",
"Agoseris heterophylla",
"Agoseris parviflora",
"Agrimonia gryposepala",
"Agrimonia pubescens",
"Agrimonia rostellata",
"Agrimonia striata",
"Ambrosia psilostachya",
"Ambrosia tomentosa",
"Ambrosia trifida",
"Ampelamus laevis",
"Amsinckia douglasiana",
"Amsinckia lycopsoides",
"Amsinckia menziesii",
"Amsinckia menziesii var. intermedia",
"Androsace occidentalis",
"Anemone alpina",
"Anemone canadensis",
"Anemone caroliniana",
"Anemone cylindrica",
"Anemone deltoidea",
"Anemone drummondii",
"Anemone multifida",
"Anemone nemorosa",
"Anemone occidentalis",
"Anemone piperi",
"Anemone quinquefolia",
"Anemone virginiana",
"Angelica arguta",
"Apium annuum",
"Arabidopsis lyrata",
"Arabidopsis thaliana",
"Arabis hirsuta",
"Arabis hirsuta var. pycnocarpa",
"Argemone ochroleuca",
"Argemone polyanthemos",
"Artemisia biennis",
"Artemisia ludoviciana",
"Artemisia serrata",
"Symphyotrichum lanceolatum",
"Aster roscidus",
"Astragalus alpinus",
"Astragalus beckwithii var. purpureus",
"Astragalus canadensis",
"Astragalus cibarius",
"Astragalus gambelianus",
"Astragalus nuttallianus",
"Astragalus pectinatus",
"Astragalus pectinatus",
"Astragalus spaldingii",
"Atriplex argentea",
"Atriplex lentiformis",
"Atriplex patula",
"Atriplex prostrata subsp calotheca",
"Barbarea vulgaris",
"Bidens alba var. radiata",
"Bidens aristosa",
"Bidens bidentoides",
"Bidens bipinnata",
"Bidens cernua",
"Bidens comosa",
"Bidens connata",
"Bidens cynapiifolia",
"Bidens frondosa",
"Bidens discoidea",
"Bidens laevis",
"Bidens pilosa",
"Bidens trichosperma",
"Bidens vulgata",
"Boechera canadensis",
"Boechera dentata",
"Boechera holboellii",
"Boechera holboellii var. secunda",
"Boechera laevigata",
"Boechera sparsiflora",
"Boechera stricta",
"Brachiaria fasciculata",
"Brassica cretica",
"Brickellia diffusa",
"Bromus inermis",
"Buglossoides arvensis",
"Cakile edentula",
"Calandrinia breweri",
"Calandrinia ciliata",
"Camissonia dentata subsp littoralis",
"Capnoides sempervirens",
"Capsella bursa-pastoris",
"Cardamine angustata",
"Cardamine bulbosa",
"Cardamine concatenata",
"Cardamine cordifolia",
"Cardamine digitata",
"Cardamine diphylla",
"Cardamine glacialis",
"Cardamine heptaphylla",
"Cardamine hirsuta",
"Cardamine nuttallii",
"Cardamine occidentalis",
"Cardamine oligosperma",
"Cardamine parviflora",
"Cardamine parviflora var. arenicola",
"Cardamine pensylvanica",
"Castilleja tenuis",
"Cayaponia americana",
"Cayaponia laciniosa",
"Cayaponia racemosa",
"Cerastium crassipes",
"Celtis laevigata",
"Celtis occidentalis",
"Cerastium arvense",
"Cerastium brachypodum",
"Cerastium fontanum subsp vulgare",
"Cerastium glomeratum",
"Cerastium nutans",
"Cerastium oreophilum",
"Cerastium semidecandrum",
"Chenopodium desiccatum var. leptophylloides",
"Chenopodium incanum",
"Chenopodium fremontii",
"Chenopodium leptophyllum",
"Chenopodium simplex",
"Chenopodium hybridum",
"Chenopodium macrospermum",
"Chenopodium macrospermum subsp salsum",
"Chenopodium murale",
"Chloris virgata",
"Chorizanthe diffusa",
"Chrysosplenium iowense",
"Cichorium intybus",
"Cicuta maculata",
"Cistanthe umbellata",
"Citrullus lanatus",
"Clarkia dudleyana",
"Clarkia purpurea subsp quadrivulnera",
"Clarkia rhomboidea",
"Claytonia lanceolata",
"Claytonia linearis",
"Claytonia parviflora",
"Claytonia perfoliata",
"Claytonia virginica",
"Clibadium surinamense",
"Coccinia grandis",
"Cochlearia officinalis",
"Collinsia parviflora",
"Collinsia sparsiflora",
"Collomia grandiflora",
"Collomia heterophylla",
"Collomia linearis",
"Conioselinum chinense",
"Conioselinum pacificum",
"Convolvulus arvensis",
"Corydalis aurea",
"Corydalis aurea subsp occidentalis",
"Corydalis flavula",
"Corydalis micrantha",
"Corydalis solida",
"Crepis acuminata",
"Cryptantha affinis",
"Cryptantha ambigua",
"Cryptantha barbigera",
"Cryptantha fendleri",
"Cryptantha simulans",
"Cryptantha torreyana",
"Cryptantha watsonii",
"Cyanus segetum",
"Cyclospermum leptophyllum",
"Cyclachaena xanthiifolia",
"Cynodon dactylon",
"Delphinium depauperatum",
"Descurainia californica",
"Descurainia depressa",
"Descurainia incana",
"Descurainia incana subsp incisa",
"Descurainia incana subsp procera",
"Descurainia incisa subsp incisa",
"Descurainia longepedicellata",
"Descurainia pinnata",
"Descurainia pinnata subsp brachycarpa",
"Descurainia pinnata subsp intermedia",
"Descurainia pinnata subsp ochroleuca",
"Descurainia sophia",
"Dicentra canadensis",
"Dicentra cucullaria",
"Dicentra formosa",
"Dipsacus fullonum",
"Draba nemorosa",
"Draba cuneifolia",
"Draba reptans",
"Draba stenoloba",
"Dracocephalum parviflorum",
"Duchesnea indica",
"Dysphania ambrosioides",
"Echinospermum virginicum",
"Elephantopus carolinianus",
"Eleusine indica",
"Ellisia nyctelea",
"Elymus canadensis",
"Elymus junceus",
"Elymus repens",
"Epilobium coloratum",
"Epilobium latifolium",
"Epilobium minutum",
"Eragrostis pectinacea",
"Erechtites hieracifolia",
"Eremothera chamaenerioides",
"Eremothera minor",
"Erigeron annuus",
"Erigeron bonariensis",
"Erigeron canadensis",
"Erigeron divergens",
"Erigeron philadelphicus",
"Eriogonum deflexum",
"Eriogonum thurberi",
"Erysimum asperum",
"Erysimum capitatum",
"Eucrypta micrantha",
"Euphorbia cordifolia",
"Euphorbia glyptosperma",
"Euphorbia humistrata",
"Euphorbia hypericifolia",
"Euphorbia maculata",
"Euphorbia nutans",
"Euphorbia prostrata",
"Euphorbia serpens",
"Euphorbia serpyllifolia",
"Euphorbia serpyllifolia subsp hirtula",
"Euphorbia spathulata",
"Euphorbia stictospora",
"Eutrema edwardsii",
"Fallopia scandens",
"Filago germanica",
"Floerkea proserpinacoides",
"Fragaria virginiana",
"Galinsoga parviflora",
"Galium aparine",
"Galium asprellum",
"Galium bifolium",
"Galium boreale",
"Galium concinnum",
"Galium tinctorium",
"Galium trifidum",
"Galium trifidum subsp brevipes",
"Galium triflorum",
"Gaura mollis",
"Geranium bicknellii",
"Geranium caroliniaum",
"Geranium maculatum",
"Geranium oreganum",
"Geranium richardsonii",
"Geranium robertianum",
"Geranium texanum",
"Geranium viscosissimum",
"Geranium vulcanicola",
"Geum aleppicum",
"Geum canadense",
"Geum macrophyllum",
"Geum rivale",
"Geum triflorum",
"Geum virginianum",
"Gnaphalium pensylvanicum",
"Gnaphalium purpureum",
"Gonolobus caroliniensis",
"Gonolobus suberosus",
"Grayia spinosa",
"Grossularia menziesii",
"Guillenia lasiophylla",
"Hackelia cinerea",
"Hackelia floribunda",
"Hackelia micrantha",
"Hackelia patens",
"Hasteola suaveolens",
"Hedeoma hispida",
"Hedeoma pulegioides",
"Hedysarum alpinum",
"Hedysarum mackenzii",
"Helianthus argophyllus",
"Helianthus decapetalus",
"Helianthus divaricatus",
"Helianthus doronicoides",
"Helianthus giganteus",
"Helianthus grosseserratus",
"Helianthus hirsutus",
"Helianthus laetiflorus",
"Helianthus maximiliani",
"Helianthus nuttallii",
"Helianthus occidentalis",
"Helianthus pauciflorus",
"Helianthus pauciflorus subsp subrhomboideus",
"Helianthus petiolaris",
"Helianthus scaberrimus",
"Helianthus subtuberosus",
"Helianthus tuberosus",
"Heliocarpus americanus",
"Erigeron scaposus",
"Erodium cicutarium",
"Erysimum cheiranthoides",
"Draba verna",
"Euphorbia indica",
"Euphrasia antarctica",
"Euphrasia officinalis",
"Fallopia convolvulus",
"Fallopia dumetorum",
"Galium mollugo",
"Galium spurium",
"Geranium pusillum",
"Geranium rotundifolium",
"Geranium sibiricum",
"Hesperis matronalis",
"Hordeum murinum",
"Houstonia caerulea",
"Houstonia pusilla",
"Hydrophyllum capitatum",
"Hydrophyllum fendleri",
"Hydrophyllum fendleri var. albifrons",
"Hydrophyllum macrophyllum",
"Hydrophyllum occidentale",
"Hydrophyllum tenuipes",
"Impatiens capensis",
"Impatiens pallida",
"Isopyrum hallii",
"Krigia biflora",
"Krigia cespitosa",
"Krigia dandelion",
"Krigia virginica",
"Lactuca biennis",
"Lactuca canadensis",
"Lactuca elongata",
"Lactuca floridana",
"Lactuca graminifolia",
"Lactuca hirsuta",
"Lactuca leucophaea",
"Lactuca ludoviciana",
"Laportea canadensis",
"Lappula occidentalis",
"Lappula occidentalis var. cupulata",
"Lappula occidentalis var. occidentalis",
"Lappula virginiana",
"Lathyrus japonicus subsp maritimus",
"Lathyrus nevadensis subsp lanceolatus",
"Lathyrus venosus",
"Lipochaeta integrifolia",
"Leavenworthia exigua",
"Lepidium austrinum",
"Lepidium dictyotum",
"Lepidium lasiocarpum",
"Lepidium latipes",
"Lepidium nitidum",
"Lepidium ramosissimum",
"Lepidium thurberi",
"Lepidium virginicum",
"Lepidium virginicum subsp menziesii",
"Lesquerella purpurea",
"Lewisia cotyledon",
"Ligusticum scoticum",
"Linaria canadensis",
"Linum sulcatum",
"Lithophragma bulbiferum",
"Lithophragma parviflorum",
"Lupinus affinis",
"Lupinus argenteus var. tenellus",
"Lupinus hirsutissimus",
"Lupinus lepidus",
"Lupinus minimus",
"Lupinus odoratus",
"Lupinus sericeus",
"Lupinus subvexus",
"Hypechusa tricolor",
"Hypochaeris chillensis",
"Iberis amara",
"Iberis sempervirens",
"Lactuca saligna",
"Lactuca serriola",
"Lactuca tatarica",
"Lamium amplexicaule",
"Lampsana sp",
"Lappula patula",
"Lepidium apetalum",
"Lepidium densiflorum",
"Lepidium didymum",
"Lobularia maritima",
"Madia gracilis",
"Matelea obliqua",
"Melampyrum lineare",
"Melampyrum lineare var. americanum",
"Melothria sp",
"Mentha arvensis",
"Mentha canadensis",
"Mertensia paniculata",
"Microsteris gracilis",
"Mimulus breweri",
"Mimulus guttatus",
"Mimulus pulsiferae",
"Mimulus tricolor",
"Mirabilis alipes",
"Mirabilis laevis",
"Mirabilis nyctaginea",
"Mirabilis nyctaginea var. angustifolia",
"Monolepis nuttalliana",
"Muhlenbergia mexicana",
"Myosotis alpestris",
"Myosotis laxa",
"Myosotis macrosperma",
"Myosotis verna",
"Nabalus altissimus",
"Navarretia intertexta",
"Nemophila breviflora",
"Nemophila kirtleyi",
"Nemophila microcalyx",
"Nemophila parviflora",
"Nemophila pedunculata",
"Nemophila pedunculata var. sepulta",
"Nemophila pulchella",
"Nicotiana attenuata",
"Nicotiana bigelovii",
"Nicotiana bigelovii var. quadricoloris",
"Nicotiana repanda",
"Nicotiana trigonophylla",
"Oenothera flava",
"Oenothera humifusa",
"Oenothera laciniata",
"Oenothera primiveris",
"Oenothera villosa subsp strigosa",
"Ottleya utahensis",
"Oxytropis deflexa",
"Oxytropis nigrescens",
"Melilotus officinalis",
"Melilotus officinalis subsp alba",
"Mitracarpus hirtus",
"Momordica balsamina",
"Mukia maderaspatana",
"Myosotis arvensis",
"Myosotis discolor",
"Myosotis stricta",
"Myosotis sylvatica",
"Nicotiana benthamiana",
"Nicotiana caesia",
"Nicotiana glauca",
"Nicotiana gossei",
"Nicotiana longiflora",
"Nicotiana stocktonii",
"Oenothera mollissima",
"Parietaria debilis",
"Parietaria pensylvanica",
"Parthenocissus quinquefolia",
"Parthenocissus quinquefolia f. hirsuta",
"Phacelia congesta",
"Phacelia hastata var. leucophylla",
"Phacelia heterophylla",
"Phacelia linearis",
"Phacelia mutabilis",
"Phacelia parryi",
"Physaria gordonii",
"Physostegia parviflora",
"Plagiobothrys cognatus",
"Plagiobothrys hispidulus",
"Plagiobothrys scopulorum",
"Plagiobothrys tenellus",
"Planodes virginicum",
"Plantago aristata",
"Plantago cordata",
"Plantago erecta",
"Plantago patagonica",
"Plantago pusilla",
"Plantago rhodosperma",
"Plantago rugelii",
"Plantago spinulosa",
"Plantago virginica",
"Polygonum douglasii",
"Polygonum polygaloides subsp confertiflorum",
"Polygonum ramosissimum",
"Polygonum aviculare",
"Potentilla canadensis",
"Potentilla gracilis",
"Potentilla gracilis var. fastigiata",
"Potentilla gracilis var. flabelliformis",
"Potentilla norvegica",
"Potentilla norvegica subsp hirsuta",
"Potentilla pulcherrima",
"Potentilla rivalis",
"Pseudostellaria jamesiana",
"Pterostegia drymarioides",
"Pyrrhopappus carolinianus",
"Parthenium hysterophorus",
"Pericallis cruenta",
"Phalaris aquatica",
"Piptothrix areolaris",
"Polypsecadium magellanicum",
"Vitis riparia",
"Setaria magna",
"Sicyos angulatus",
"Vicia gigantea",
"Rorippa palustris",
"Ranunculus abortivus",
"Ranunculus acriformis",
"Ranunculus fascicularis",
"Ranunculus hispidus",
"Ranunculus pensylvanicus",
"Ranunculus recurvatus",
"Ranunculus septentrionalis",
"Ranunculus uncinatus",
"Ribes cynosbati",
"Ribes divaricatum",
"Ribes glandulosum",
"Ribes hirtellum",
"Ribes menziesii",
"Ribes oxyacanthoides",
"Ribes triste",
"Rorippa curvisiliqua",
"Rorippa islandica",
"Rubus allegheniensis",
"Rorippa teres",
"Rubus argutus",
"Rubus canadensis",
"Rubus flagellaris",
"Rubus hispidus",
"Rubus leucodermis",
"Rubus spectabilis",
"Rubus ursinus subsp macropetalus",
"Sairocarpus nuttallianus",
"Salvia carduacea",
"Salvia reflexa",
"Scrophularia leporella",
"Silene acaulis subsp subacaulescens",
"Silene antirrhina",
"Silphium integrifolium",
"Silphium laciniatum",
"Silphium perfoliatum",
"Silphium terebinthinaceum",
"Silphium trifoliatum",
"Smilax sp",
"Solidago gigantea",
"Solidago rigida",
"Solidago sempervirens",
"Solidago serotina",
"Spermacoce eryngioides",
"Sporobolus cryptandrus",
"Sporobolus neglectus",
"Stanleya pinnata",
"Stellaria longipes",
"Stellaria pubera",
"Streptanthella longirostris",
"Streptanthus carinatus subsp arizonicus",
"Symphyotrichum ascendens",
"Symphyotrichum chilense",
"Symphyotrichum ciliolatum",
"Symphyotrichum cordifolium",
"Symphyotrichum laeve",
"Symphyotrichum oblongifolium",
"Symphyotrichum praealtum",
"Symphyotrichum puniceum",
"Symphyotrichum spathulatum",
"Symphyotrichum tradescantii",
"Symphyotrichum undulatum",
"Setaria viridis",
"Ranunculus acris",
"Ranunculus bulbosus",
"Ranunculus minutiflorus",
"Ranunculus peduncularis",
"Ranunculus repens",
"Rubus parvifolius",
"Rubus laciniatus",
"Rumex acetosa",
"Rumex acetosella",
"Rumex crispus",
"Sibara pinnata",
"Silene gallica",
"Silene latifolia",
"Sinapis arvensis var. orientalis",
"Sisymbrium altissimum",
"Sisymbrium irio",
"Sisymbrium officinale",
"Sonchus arvensis",
"Sonchus asper",
"Sonchus gangliformis",
"Sonchus oleraceus",
"Spergula arvensis",
"Spergularia rubra",
"Stellaria media",
"Teucrium canadense",
"Thalictrum pubescens",
"Thysanocarpus curvipes",
"Trautvetteria caroliniensis",
"Triumfetta lappula",
"Turritis glabra",
"Urtica dioica",
"Urtica dioica subsp gracilis",
"Valeriana occidentalis",
"Valeriana sitchensis",
"Valerianella radiata",
"Verbena hastata",
"Verbesina encelioides",
"Verbesina encelioides var. exauriculata",
"Vernonia baldwinii",
"Vernonia noveboracensis",
"Veronica alpina",
"Veronica americana",
"Veronica anagallis-aquatica",
"Veronica peregrina",
"Veronica serpyllifolia",
"Veronica serpyllifolia subsp humifusa",
"Viburnum acerifolium",
"Viburnum cassinoides",
"Viburnum dentatum",
"Viburnum nudum",
"Viburnum pubescens",
"Viburnum rufotomentosum",
"Viburnum trilobum",
"Vicia americana",
"Vicia linearis",
"Vicia ludoviciana",
"Vicia sparsifolia",
"Vitis californica",
"Vitis caribaea",
"Vitis baileyana",
"Vitis cinerea",
"Vitis cinerea var. floridana",
"Vitis rupestris",
"Vitis tiliifolia",
"Vitis x doaniana",
"Whipplea modesta",
"Zinnia peruviana",
"Trifolium dubium",
"Veronica arvensis",
"Vicia cracca",
"Vicia hirsuta",
"Vicia sepium",
"Viola arvensis",
"Vitis davidii",
"Vitis piasezkii") ~ "wild")) %>%

#code in native status

mutate(native_status = case_when(cur_host %in% c("Acalypha virginica",
"Achyronychia cooperi",
"Acmella oppositifolia",
"Acmispon americanus",
"Acmispon americanus",
"Aconitum columbianum",
"Aconitum delphinifolium",
"Agastache mexicana",
"Agastache nepetoides",
"Agastache scrophulariifolia",
"Ageratina altissima",
"Ageratina aromatica",
"Agoseris aurantiaca",
"Agoseris glauca",
"Agoseris grandiflora",
"Agoseris heterophylla",
"Agoseris parviflora",
"Agrimonia gryposepala",
"Agrimonia pubescens",
"Agrimonia rostellata",
"Agrimonia striata",
"Allium schoenoprasum",
"Ambrosia artemisiifolia",
"Ambrosia psilostachya",
"Ambrosia tomentosa",
"Ambrosia trifida",
"Ampelamus laevis",
"Amsinckia douglasiana",
"Amsinckia lycopsoides",
"Amsinckia menziesii",
"Amsinckia menziesii var. intermedia",
"Androsace occidentalis",
"Anemone alpina",
"Anemone canadensis",
"Anemone caroliniana",
"Anemone cylindrica",
"Anemone deltoidea",
"Anemone drummondii",
"Anemone hepatica",
"Anemone hepatica var. acuta",
"Anemone multifida",
"Anemone occidentalis",
"Anemone piperi",
"Anemone quinquefolia",
"Anemone virginiana",
"Angelica arguta",
"Arabidopsis lyrata",
"Arabis hirsuta",
"Arabis hirsuta var. pycnocarpa",
"Argemone ochroleuca",
"Argemone polyanthemos",
"Artemisia biennis",
"Artemisia douglasiana",
"Artemisia ludoviciana",
"Artemisia serrata",
"Symphyotrichum lanceolatum",
"Aster roscidus",
"Astragalus alpinus",
"Astragalus beckwithii var. purpureus",
"Astragalus canadensis",
"Astragalus cibarius",
"Astragalus gambelianus",
"Astragalus nuttallianus",
"Astragalus pectinatus",
"Astragalus spaldingii",
"Atriplex argentea",
"Atriplex lentiformis",
"Bidens aristosa",
"Bidens bidentoides",
"Bidens bipinnata",
"Bidens cernua",
"Bidens comosa",
"Bidens connata",
"Bidens frondosa",
"Bidens discoidea",
"Bidens laevis",
"Bidens trichosperma",
"Bidens vulgata",
"Boechera canadensis",
"Boechera dentata",
"Boechera laevigata",
"Boechera sparsiflora",
"Boechera stricta",
"Brachiaria fasciculata",
"Brickellia diffusa",
"Cakile edentula",
"Calandrinia breweri",
"Calandrinia ciliata",
"Camissonia dentata subsp littoralis",
"Capnoides sempervirens",
"Capsicum annuum",
"Cardamine angustata",
"Cardamine bulbosa",
"Cardamine concatenata",
"Cardamine cordifolia",
"Cardamine digitata",
"Cardamine diphylla",
"Cardamine nuttallii",
"Cardamine occidentalis",
"Cardamine oligosperma",
"Cardamine parviflora",
"Cardamine parviflora var. arenicola",
"Cardamine pensylvanica",
"Castilleja tenuis",
"Cayaponia americana",
"Celtis laevigata",
"Celtis occidentalis",
"Cerastium arvense",
"Cerastium brachypodum",
"Cerastium fontanum subsp vulgare",
"Cerastium nutans",
"Cerastium oreophilum",
"Cercis canadensis",
"Chenopodium berlandieri",
"Chenopodium capitatum",
"Chenopodium desiccatum var. leptophylloides",
"Chenopodium incanum",
"Chenopodium fremontii",
"Chenopodium leptophyllum",
"Chenopodium simplex",
"Chloris virgata",
"Chorizanthe diffusa",
"Chrysosplenium iowense",
"Cicuta maculata",
"Cistanthe umbellata",
"Clarkia amoena",
"Clarkia dudleyana",
"Clarkia purpurea subsp quadrivulnera",
"Clarkia rhomboidea",
"Claytonia lanceolata",
"Claytonia linearis",
"Claytonia parviflora",
"Claytonia perfoliata",
"Claytonia virginica",
"Cochlearia officinalis",
"Collinsia parviflora",
"Collinsia sparsiflora",
"Collomia grandiflora",
"Collomia heterophylla",
"Collomia linearis",
"Conioselinum chinense",
"Conioselinum pacificum",
"Coreopsis grandiflora",
"Corydalis aurea",
"Corydalis aurea subsp occidentalis",
"Corydalis flavula",
"Corydalis micrantha",
"Crepis acuminata",
"Cryptantha affinis",
"Cryptantha ambigua",
"Cryptantha barbigera",
"Cryptantha fendleri",
"Cryptantha simulans",
"Cryptantha torreyana",
"Cryptantha watsonii",
"Cyclachaena xanthiifolia",
"Cynodon dactylon",
"Delphinium depauperatum",
"Descurainia californica",
"Descurainia depressa",
"Descurainia incana",
"Descurainia incana subsp incisa",
"Descurainia incana subsp procera",
"Descurainia incisa subsp incisa",
"Descurainia longepedicellata",
"Descurainia pinnata",
"Descurainia pinnata subsp brachycarpa",
"Descurainia pinnata subsp intermedia",
"Descurainia pinnata subsp ochroleuca",
"Dicentra canadensis",
"Dicentra cucullaria",
"Dicentra formosa",
"Echinocystis lobata",
"Draba cuneifolia",
"Draba reptans",
"Draba stenoloba",
"Dracocephalum parviflorum",
"Duchesnea indica",
"Dysphania ambrosioides",
"Echinospermum virginicum",
"Elephantopus carolinianus",
"Ellisia nyctelea",
"Elymus canadensis",
"Elymus junceus",
"Epilobium coloratum",
"Epilobium latifolium",
"Epilobium minutum",
"Eragrostis pectinacea",
"Erechtites hieracifolia",
"Eremothera chamaenerioides",
"Eremothera minor",
"Erigeron annuus",
"Erigeron canadensis",
"Erigeron divergens",
"Erigeron philadelphicus",
"Eriogonum deflexum",
"Eriogonum thurberi",
"Erysimum asperum",
"Erysimum capitatum",
"Eucrypta micrantha",
"Euphorbia cordifolia",
"Euphorbia glyptosperma",
"Euphorbia humistrata",
"Euphorbia hypericifolia",
"Euphorbia maculata",
"Euphorbia nutans",
"Euphorbia prostrata",
"Euphorbia serpens",
"Euphorbia serpyllifolia",
"Euphorbia serpyllifolia subsp hirtula",
"Euphorbia spathulata",
"Euphorbia stictospora",
"Eutrema edwardsii",
"Fallopia scandens",
"Filago germanica",
"Floerkea proserpinacoides",
"Fragaria virginiana",
"Galinsoga parviflora",
"Galium aparine",
"Galium asprellum",
"Galium bifolium",
"Galium boreale",
"Galium concinnum",
"Galium tinctorium",
"Galium trifidum",
"Galium trifidum subsp brevipes",
"Galium triflorum",
"Gaura mollis",
"Geranium bicknellii",
"Geranium caroliniaum",
"Geranium maculatum",
"Geranium oreganum",
"Geranium richardsonii",
"Geranium robertianum",
"Geranium texanum",
"Geranium viscosissimum",
"Geranium vulcanicola",
"Geum aleppicum",
"Geum canadense",
"Geum macrophyllum",
"Geum rivale",
"Geum triflorum",
"Geum virginianum",
"Gnaphalium pensylvanicum",
"Gnaphalium purpureum",
"Gonolobus caroliniensis",
"Gonolobus suberosus",
"Grayia spinosa",
"Grossularia menziesii",
"Guillenia lasiophylla",
"Hackelia cinerea",
"Hackelia floribunda",
"Hackelia micrantha",
"Hackelia patens",
"Hasteola suaveolens",
"Hedeoma hispida",
"Hedeoma pulegioides",
"Hedysarum alpinum",
"Hedysarum mackenzii",
"Helianthus argophyllus",
"Helianthus decapetalus",
"Helianthus divaricatus",
"Helianthus doronicoides",
"Helianthus giganteus",
"Helianthus grosseserratus",
"Helianthus hirsutus",
"Helianthus laetiflorus",
"Helianthus maximiliani",
"Helianthus nuttallii",
"Helianthus occidentalis",
"Helianthus pauciflorus",
"Helianthus pauciflorus subsp subrhomboideus",
"Helianthus petiolaris",
"Helianthus scaberrimus",
"Helianthus subtuberosus",
"Helianthus tuberosus",
"Heliocarpus americanus",
"Eupatorium purpureum",
"Helianthus annuus",
"Houstonia caerulea",
"Houstonia pusilla",
"Hydrophyllum capitatum",
"Hydrophyllum fendleri",
"Hydrophyllum fendleri var. albifrons",
"Hydrophyllum macrophyllum",
"Hydrophyllum occidentale",
"Hydrophyllum tenuipes",
"Impatiens capensis",
"Impatiens pallida",
"Isopyrum hallii",
"Krigia biflora",
"Krigia cespitosa",
"Krigia dandelion",
"Krigia virginica",
"Lactuca biennis",
"Lactuca canadensis",
"Lactuca elongata",
"Lactuca floridana",
"Lactuca graminifolia",
"Lactuca hirsuta",
"Lactuca leucophaea",
"Lactuca ludoviciana",
"Laportea canadensis",
"Lappula occidentalis",
"Lappula occidentalis var. cupulata",
"Lappula occidentalis var. occidentalis",
"Lappula virginiana",
"Lathyrus japonicus subsp maritimus",
"Lathyrus nevadensis subsp lanceolatus",
"Lathyrus venosus",
"Lipochaeta integrifolia",
"Leavenworthia exigua",
"Lepidium austrinum",
"Lepidium dictyotum",
"Lepidium lasiocarpum",
"Lepidium latipes",
"Lepidium nitidum",
"Lepidium ramosissimum",
"Lepidium thurberi",
"Lepidium virginicum",
"Lepidium virginicum subsp menziesii",
"Lesquerella purpurea",
"Lewisia cotyledon",
"Ligusticum scoticum",
"Linaria canadensis",
"Linum sulcatum",
"Lithophragma bulbiferum",
"Lithophragma parviflorum",
"Lupinus affinis",
"Lupinus argenteus var. tenellus",
"Lupinus hirsutissimus",
"Lupinus lepidus",
"Lupinus minimus",
"Lupinus odoratus",
"Lupinus sericeus",
"Lupinus subvexus",
"Hydrophyllum virginianum",
"Lagenaria siceraria",
"Lupinus bicolor",
"Lupinus densiflorus",
"Lupinus perennis",
"Lupinus polyphyllus",
"Madia gracilis",
"Matelea obliqua",
"Melampyrum lineare",
"Melampyrum lineare var. americanum",
"Melothria sp",
"Mentha arvensis",
"Mentha canadensis",
"Mertensia paniculata",
"Microsteris gracilis",
"Mimulus breweri",
"Mimulus guttatus",
"Mimulus pulsiferae",
"Mimulus tricolor",
"Mirabilis alipes",
"Mirabilis laevis",
"Mirabilis nyctaginea",
"Mirabilis nyctaginea var. angustifolia",
"Monolepis nuttalliana",
"Muhlenbergia mexicana",
"Myosotis alpestris",
"Myosotis laxa",
"Myosotis macrosperma",
"Myosotis verna",
"Nabalus altissimus",
"Navarretia intertexta",
"Nemophila breviflora",
"Nemophila kirtleyi",
"Nemophila microcalyx",
"Nemophila parviflora",
"Nemophila pedunculata",
"Nemophila pedunculata var. sepulta",
"Nemophila pulchella",
"Nicotiana attenuata",
"Nicotiana bigelovii",
"Nicotiana bigelovii var. quadricoloris",
"Nicotiana repanda",
"Nicotiana trigonophylla",
"Oenothera flava",
"Oenothera humifusa",
"Oenothera laciniata",
"Oenothera primiveris",
"Oenothera villosa subsp strigosa",
"Ottleya utahensis",
"Oxytropis deflexa",
"Oxytropis nigrescens",
"Monarda didyma",
"Oenothera biennis",
"Oenothera pallida",
"Oenothera speciosa",
"Papaver nudicaule",
"Parietaria debilis",
"Parietaria pensylvanica",
"Parthenocissus quinquefolia",
"Parthenocissus quinquefolia f. hirsuta",
"Phacelia congesta",
"Phacelia hastata var. leucophylla",
"Phacelia heterophylla",
"Phacelia linearis",
"Phacelia mutabilis",
"Phacelia parryi",
"Physaria gordonii",
"Physostegia parviflora",
"Plagiobothrys cognatus",
"Plagiobothrys hispidulus",
"Plagiobothrys scopulorum",
"Plagiobothrys tenellus",
"Planodes virginicum",
"Plantago aristata",
"Plantago cordata",
"Plantago erecta",
"Plantago patagonica",
"Plantago pusilla",
"Plantago rhodosperma",
"Plantago rugelii",
"Plantago spinulosa",
"Plantago virginica",
"Polygonum douglasii",
"Polygonum polygaloides subsp confertiflorum",
"Polygonum ramosissimum",
"Polygonum aviculare",
"Potentilla canadensis",
"Potentilla gracilis",
"Potentilla gracilis var. fastigiata",
"Potentilla gracilis var. flabelliformis",
"Potentilla norvegica",
"Potentilla norvegica subsp hirsuta",
"Potentilla pulcherrima",
"Potentilla rivalis",
"Pseudostellaria jamesiana",
"Pterostegia drymarioides",
"Pyrrhopappus carolinianus",
"Penstemon angustifolius",
"Phlox divaricata",
"Phlox paniculata",
"Physostegia virginiana",
"Plantago ovata",
"Plantago princeps var. princeps",
"Vitis riparia",
"Setaria magna",
"Sicyos angulatus",
"Vicia gigantea",
"Rorippa palustris",
"Ranunculus abortivus",
"Ranunculus acriformis",
"Ranunculus fascicularis",
"Ranunculus hispidus",
"Ranunculus pensylvanicus",
"Ranunculus recurvatus",
"Ranunculus septentrionalis",
"Ranunculus uncinatus",
"Ribes cynosbati",
"Ribes divaricatum",
"Ribes glandulosum",
"Ribes hirtellum",
"Ribes menziesii",
"Ribes oxyacanthoides",
"Ribes triste",
"Rorippa curvisiliqua",
"Rorippa islandica",
"Rubus allegheniensis",
"Rorippa teres",
"Rubus argutus",
"Rubus canadensis",
"Rubus flagellaris",
"Rubus hispidus",
"Rubus leucodermis",
"Rubus spectabilis",
"Rubus ursinus subsp macropetalus",
"Sairocarpus nuttallianus",
"Salvia carduacea",
"Salvia reflexa",
"Scrophularia leporella",
"Silene acaulis subsp subacaulescens",
"Silene antirrhina",
"Silphium integrifolium",
"Silphium laciniatum",
"Silphium perfoliatum",
"Silphium terebinthinaceum",
"Silphium trifoliatum",
"Smilax sp",
"Solidago gigantea",
"Solidago rigida",
"Solidago sempervirens",
"Solidago serotina",
"Solidago sphacelata",
"Spermacoce eryngioides",
"Sporobolus cryptandrus",
"Sporobolus neglectus",
"Stanleya pinnata",
"Stellaria longipes",
"Stellaria pubera",
"Streptanthella longirostris",
"Streptanthus carinatus subsp arizonicus",
"Symphyotrichum ascendens",
"Symphyotrichum chilense",
"Symphyotrichum ciliolatum",
"Symphyotrichum cordifolium",
"Symphyotrichum laeve",
"Symphyotrichum oblongifolium",
"Symphyotrichum praealtum",
"Symphyotrichum puniceum",
"Symphyotrichum spathulatum",
"Symphyotrichum tradescantii",
"Symphyotrichum undulatum",
"Vitis vulpina",
"Zea mays",
"Vitis aestivalis",
"Vitis aestivalis var. bourquiniana",
"Vitis cordifolia",
"Vitis labrusca",
"Ratibida pinnata",
"Rubus idaeus subsp strigosus",
"Rudbeckia fulgida",
"Rudbeckia hirta",
"Rudbeckia laciniata",
"Rudbeckia sp",
"Rudbeckia triloba",
"Scrophularia marylandica",
"Scrophularia lanceolata",
"Symphyotrichum lateriflorum",
"Symphyotrichum novae-angliae",
"Teucrium canadense",
"Thalictrum pubescens",
"Thysanocarpus curvipes",
"Trautvetteria caroliniensis",
"Triumfetta lappula",
"Turritis glabra",
"Urtica dioica",
"Urtica dioica subsp gracilis",
"Valeriana occidentalis",
"Valeriana sitchensis",
"Valerianella radiata",
"Verbena hastata",
"Verbesina encelioides",
"Verbesina encelioides var. exauriculata",
"Vernonia baldwinii",
"Vernonia noveboracensis",
"Veronica alpina",
"Veronica americana",
"Veronica anagallis-aquatica",
"Veronica peregrina",
"Veronica serpyllifolia",
"Veronica serpyllifolia subsp humifusa",
"Viburnum acerifolium",
"Viburnum cassinoides",
"Viburnum dentatum",
"Viburnum nudum",
"Viburnum pubescens",
"Viburnum rufotomentosum",
"Viburnum trilobum",
"Vicia americana",
"Vicia linearis",
"Vicia ludoviciana",
"Vicia sparsifolia",
"Vitis californica",
"Vitis caribaea",
"Vitis baileyana",
"Vitis cinerea",
"Vitis cinerea var. floridana",
"Vitis rupestris",
"Vitis tiliifolia",
"Vitis x doaniana",
"Whipplea modesta",
"Zinnia peruviana",
"Vaccinium sp",
"Viola bicolor",
"Viola tricolor",
"Viola tricolor f. tenella",
"Vitis bicolor",
"Vitis rotundifolia",
"Vitis rufotomentosa",
"Vitis simpsonii") ~ "native",
cur_host %in% c("Allium cepa",
"Acacia sp",
"Acanthospermum australe",
"Acanthospermum humile",
"Agrimonia eupatoria",
"Agropyron cristatum",
"Agrostemma githago",
"Allamanda cathartica",
"Allium nigrum",
"Allium sativum",
"Ampelopsis glandulosa",
"Anemone coronaria",
"Anemone dichotoma",
"Anemone nemorosa",
"Antirrhinum majus",
"Apium annuum",
"Apogon humilis",
"Arabidopsis thaliana",
"Arctotis fastuosa",
"Argyranthemum frutescens",
"Armoracia rusticana",
"Artemisia absinthium",
"Artemisia arborescens",
"Artemisia argyrophylla var. brevis",
"Astragalus pectinatus",
"Atriplex patula",
"Atriplex prostrata subsp calotheca",
"Atropa belladonna",
"Aurinia saxatilis",
"Avena byzantina",
"Avena sativa",
"Barbarea verna",
"Barbarea vulgaris",
"Beta vulgaris",
"Bidens alba var. radiata",
"Bidens cynapiifolia",
"Bidens pilosa",
"Boechera holboellii",
"Boechera holboellii var. secunda",
"Brassica cretica",
"Brassica juncea",
"Brassica napus",
"Brassica nigra",
"Brassica oleracea",
"Brassica oleracea var. capitata",
"Brassica rapa",
"Bromus inermis",
"Buglossoides arvensis",
"Callistephus chinensis",
"Camelina sativa",
"Capsella bursa-pastoris",
"Cardamine glacialis",
"Cardamine heptaphylla",
"Cardamine hirsuta",
"Cayaponia laciniosa",
"Cayaponia racemosa",
"Cerastium crassipes",
"Cerastium glomeratum",
"Cerastium semidecandrum",
"Chenopodium album",
"Chenopodium quinoa",
"Chenopodium hybridum",
"Chenopodium macrospermum",
"Chenopodium macrospermum subsp salsum",
"Chenopodium murale",
"Cicer arietinum",
"Cichorium intybus",
"Citrullus lanatus",
"Clibadium surinamense",
"Coccinia grandis",
"Colocasia antiquorum",
"Convolvulus arvensis",
"Corydalis solida",
"Cucumis anguria",
"Cucumis melo",
"Cucumis sativus",
"Cucurbita maxima",
"Cucurbita moschata",
"Cucurbita pepo",
"Cucurbita pepo subsp ovifera",
"Cyanus segetum",
"Cyclospermum leptophyllum",
"Dactylis glomerata",
"Descurainia sophia",
"Dianthus caryophyllus",
"Digitalis purpurea",
"Dipsacus fullonum",
"Draba nemorosa",
"Eleusine indica",
"Elymus repens",
"Erigeron bonariensis",
"Erigeron scaposus",
"Erodium cicutarium",
"Erysimum cheiranthoides",
"Draba verna",
"Euphorbia indica",
"Euphrasia antarctica",
"Euphrasia officinalis",
"Fallopia convolvulus",
"Fallopia dumetorum",
"Galium mollugo",
"Galium spurium",
"Geranium pusillum",
"Geranium rotundifolium",
"Geranium sibiricum",
"Hesperis matronalis",
"Hordeum murinum",
"Erysimum ◊ cheiri",
"Fagopyrum esculentum",
"Festuca arundinacea",
"Geum chiloense",
"Glycine max",
"Helichrysum bracteatum",
"Hordeum vulgare",
"Humulus lupulus",
"Humulus lupulus var. lupuloides",
"Impatiens arguta",
"Impatiens balsamina",
"Impatiens flanaganae",
"Impatiens hochstetteri",
"Impatiens walleriana",
"Lactuca sativa",
"Lathyrus odoratus",
"Lilium longiflorum",
"Lolium perenne",
"Luffa acutangula",
"Lupinus hartwegii",
"Lycopersicon esculentum",
"Hypechusa tricolor",
"Hypochaeris chillensis",
"Iberis amara",
"Iberis sempervirens",
"Lactuca saligna",
"Lactuca serriola",
"Lactuca tatarica",
"Lamium amplexicaule",
"Lampsana sp",
"Lappula patula",
"Lepidium apetalum",
"Lepidium densiflorum",
"Lepidium didymum",
"Lobularia maritima",
"Melilotus officinalis",
"Melilotus officinalis subsp alba",
"Mitracarpus hirtus",
"Momordica balsamina",
"Mukia maderaspatana",
"Myosotis arvensis",
"Myosotis discolor",
"Myosotis stricta",
"Myosotis sylvatica",
"Nicotiana benthamiana",
"Nicotiana caesia",
"Nicotiana glauca",
"Nicotiana gossei",
"Nicotiana longiflora",
"Nicotiana stocktonii",
"Oenothera mollissima",
"Matthiola incana",
"Medicago lupulina",
"Medicago sativa",
"Melia azedarach",
"Mesembryanthemum cordifolium",
"Momordica charantia",
"Monoculus hyoseroides",
"Moricandia arvensis",
"Mucuna pruriens var. utilis",
"Nasturtium officinale",
"Nicotiana stocktonii",
"Nicotiana sylvestris",
"Nicotiana tabacum",
"Nicotiana tomentosa",
"Ocimum basilicum",
"Papaver somniferum",
"Parthenium hysterophorus",
"Pericallis cruenta",
"Phalaris aquatica",
"Piptothrix areolaris",
"Polypsecadium magellanicum",
"Parthenocissus tricuspidata",
"Pastinaca sativa",
"Pennisetum glaucum",
"Pilosella aurantiaca",
"Pisum sativum",
"Plantago major",
"Plectranthus scutellarioides",
"Potentilla nepalensis",
"Setaria viridis",
"Ranunculus acris",
"Ranunculus bulbosus",
"Ranunculus minutiflorus",
"Ranunculus peduncularis",
"Ranunculus repens",
"Rubus parvifolius",
"Rubus laciniatus",
"Rumex acetosa",
"Rumex acetosella",
"Rumex crispus",
"Sibara pinnata",
"Silene gallica",
"Silene latifolia",
"Sinapis arvensis var. orientalis",
"Sisymbrium altissimum",
"Sisymbrium irio",
"Sisymbrium officinale",
"Sonchus arvensis",
"Sonchus asper",
"Sonchus gangliformis",
"Sonchus oleraceus",
"Spergula arvensis",
"Spergularia rubra",
"Stellaria media",
"Vitis vinifera",
"Rosa sp",
"Setaria italica",
"Sorghum bicolor",
"Sorghum halepense",
"Vitis 'Lindley' labrusca X vinefera",
"Tarenaya hassleriana",
"Raphanus raphanistrum",
"Raphanus raphanistrum subsp sativus",
"Rheum rhabarbarum",
"Ribes rubrum",
"Ribes uva-crispa",
"Rubus corchorifolius",
"Rubus villosus var. humifusus",
"Scabiosa atropurpurea",
"Scabiosa columbaria",
"Scrophularia nodosa",
"Secale cereale",
"Solanum tuberosum",
"Spilanthes ocymifolia",
"Spinacia oleracea",
"Trichosanthes colubrina",
"Trifolium incarnatum",
"Trifolium repens",
"Trigonella foenum-graecum",
"Triosteum perfoliatum",
"Triticum aestivum",
"Viburnum opulus",
"Viburnum sargentii",
"Viburnum tinus",
"Vicia faba",
"Vicia sativa",
"Vicia sativa subsp nigra",
"Vicia villosa",
"Vigna unguiculata",
"Vitis coignetiae") ~ "non-native",)) %>%

#Bin by decade

mutate(decade= case_when(year %in% c(1800:1809) ~ "1800",
year %in% c(1810:1819) ~ "1810",
year %in% c(1820:1829) ~ "1820",
year %in% c(1830:1839) ~ "1830",
year %in% c(1840:1849) ~ "1840",
year %in% c(1850:1859) ~ "1850",
year %in% c(1860:1869) ~ "1860",
year %in% c(1870:1879) ~ "1870",
year %in% c(1880:1889) ~ "1880",
year %in% c(1890:1899) ~ "1890",
year %in% c(1910:1919) ~ "1910",
year %in% c(1920:1929) ~ "1920",
year %in% c(1930:1939) ~ "1930",
year %in% c(1940:1949) ~ "1940",
year %in% c(1950:1959) ~ "1950",
year %in% c(1960:1969) ~ "1960",
year %in% c(1970:1979) ~ "1970",
year %in% c(1980:1989) ~ "1980",
year %in% c(1990:1999) ~ "1990",
year %in% c(2010:2020) ~ "2010",
year %in% c(2020:2029) ~ "2020",)) %>%

relocate(decade, .after=day)


Downy_mildews_tidy$cultivated_native <-paste(Downy_mildews_tidy$cultivated,Downy_mildews_tidy$native_status, sep="-")

write.table(Downy_mildews_tidy, "Downy_mildews_tidy.txt", sep="\t")



#Creating subsets of the data by Continent
North_American_downy_mildews_tidy <- subset(Downy_mildews_tidy, continent=="North America")

write.table(North_American_downy_mildews_tidy, "North_American_downy_mildews_tidy.txt", sep="\t")

#Deduplication with scrubr

North_American_downy_mildews_tidy_dedup <-dedup(North_American_downy_mildews_tidy, how="one", tolerance=1)

write.table(North_American_downy_mildews_tidy_dedup, "North_American_downy_mildews_tidy_dedup_t1_20210209-15.txt", sep="\t")
